### ISSUE TITLE
Create base structure

### ISSUE THREAD

**Issue by Monfernape** [Monfernape/shoes-rack#1]
### Description
Create a base structure of an app with following packages:
- Next 14
- Supabase
- ShadCN
- Tailwind

**Comment by nadirhussain786** [comment]
I have established the core structure of a Next.js application and integrate shadcn  , tailwind and supabase.

**Comment by Monfernape** [comment]
> I have established the core structure of a Next.js application and integrate shadcn  , tailwind and supabase.

@nadirhussain786 let's not push to main moving forward. Always create a PR
